"""Update

Revision ID: 0a18bf7d555a
Revises: 726dae1e96f6
Create Date: 2024-03-14 21:59:27.958580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0a18bf7d555a"
down_revision: Union[str, None] = "726dae1e96f6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("leads", sa.Column("email", sa.String(), nullable=True))
    op.create_index(op.f("ix_leads_email"), "leads", ["email"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_leads_email"), table_name="leads")
    op.drop_column("leads", "email")
    # ### end Alembic commands ###
