"""added email update

Revision ID: 25f44668fced
Revises: 45c779f6a94b
Create Date: 2024-03-17 23:05:23.876996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "25f44668fced"
down_revision: Union[str, None] = "45c779f6a94b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("emails", sa.Column("sendgrid_email_id", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("emails", "sendgrid_email_id")
    # ### end Alembic commands ###
