"""database update

Revision ID: 45c779f6a94b
Revises: 0a18bf7d555a
Create Date: 2024-03-17 22:28:16.102864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "45c779f6a94b"
down_revision: Union[str, None] = "0a18bf7d555a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("campaigns", sa.Column("html_content", sa.String(), nullable=True))
    op.add_column(
        "campaigns", sa.Column("sendgrid_campaign_id", sa.Integer(), nullable=True)
    )
    op.alter_column("campaigns", "name", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("customers", "name", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("deals", "name", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column(
        "deals",
        "amount",
        existing_type=sa.INTEGER(),
        type_=sa.DECIMAL(precision=10, scale=2),
        existing_nullable=True,
    )
    op.alter_column("emails", "sender", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("emails", "recipient", existing_type=sa.VARCHAR(), nullable=False)
    op.add_column("leads", sa.Column("status", sa.String(), nullable=True))
    op.alter_column(
        "leads", "name", existing_type=sa.VARCHAR(length=60), nullable=False
    )
    op.add_column("users", sa.Column("password", sa.String(), nullable=False))
    op.alter_column("users", "username", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("users", "email", existing_type=sa.VARCHAR(), nullable=False)
    op.drop_column("users", "hashed_password")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("hashed_password", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.alter_column("users", "email", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("users", "username", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_column("users", "password")
    op.alter_column("leads", "name", existing_type=sa.VARCHAR(length=60), nullable=True)
    op.drop_column("leads", "status")
    op.alter_column("emails", "recipient", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("emails", "sender", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column(
        "deals",
        "amount",
        existing_type=sa.DECIMAL(precision=10, scale=2),
        type_=sa.INTEGER(),
        existing_nullable=True,
    )
    op.alter_column("deals", "name", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("customers", "name", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("campaigns", "name", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_column("campaigns", "sendgrid_campaign_id")
    op.drop_column("campaigns", "html_content")
    # ### end Alembic commands ###
