"""Update speeling errors

Revision ID: 726dae1e96f6
Revises: f15a31ecdbd8
Create Date: 2024-03-13 21:48:52.207006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "726dae1e96f6"
down_revision: Union[str, None] = "f15a31ecdbd8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_email_tracking_email_id", table_name="email_tracking")
    op.drop_index("ix_email_tracking_id", table_name="email_tracking")
    op.drop_table("email_tracking")
    op.add_column("customers", sa.Column("created_at", sa.DateTime(), nullable=True))
    op.drop_column("customers", "create_at")
    op.add_column("leads", sa.Column("created_at", sa.DateTime(), nullable=True))
    op.drop_column("leads", "create_at")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "leads",
        sa.Column(
            "create_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
    )
    op.drop_column("leads", "created_at")
    op.add_column(
        "customers",
        sa.Column(
            "create_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
    )
    op.drop_column("customers", "created_at")
    op.create_table(
        "email_tracking",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("email_id", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "opened_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column("lead_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("customer_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["customer_id"], ["customers.id"], name="email_tracking_customer_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["lead_id"], ["leads.id"], name="email_tracking_lead_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="email_tracking_pkey"),
    )
    op.create_index("ix_email_tracking_id", "email_tracking", ["id"], unique=False)
    op.create_index(
        "ix_email_tracking_email_id", "email_tracking", ["email_id"], unique=False
    )
    # ### end Alembic commands ###
