"""Customer update

Revision ID: f15a31ecdbd8
Revises: 22ec5a92e570
Create Date: 2024-03-11 17:28:12.370798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f15a31ecdbd8"
down_revision: Union[str, None] = "22ec5a92e570"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("emails_customer_id_fkey", "emails", type_="foreignkey")
    op.drop_column("emails", "customer_id")
    op.drop_index("ix_leads_email", table_name="leads")
    op.drop_column("leads", "email")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "leads", sa.Column("email", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.create_index("ix_leads_email", "leads", ["email"], unique=False)
    op.add_column(
        "emails",
        sa.Column("customer_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        "emails_customer_id_fkey", "emails", "customers", ["customer_id"], ["id"]
    )
    # ### end Alembic commands ###
